pool:
  vmImage: 'Ubuntu 16.04'

container: mabenoit/aksengine-agent:latest

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - example/
pr:
  branches:
    include:
    - refs/heads/*
  paths:
    include:
    - example/

variables:
  location: eastus
  apiModel: kubernetes-win-vmss.json
  # define 4 more variables: subscriptionId, clientId, clientSecret and dnsPrefix in the build pipeline in UI

steps:
- bash: aks-engine version    
  displayName: 'aks-engine version'
- bash: |
    cd $(system.defaultWorkingDirectory)/example
    aks-engine deploy -s $(subscriptionId) --client-id '$(clientId)' --client-secret '$(clientSecret)' --dns-prefix $(dnsPrefix) -l $(location) --api-model $(apiModel)
  displayName: 'aks-engine deploy'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts: drop'
  inputs:
    PathtoPublish: '$(system.defaultWorkingDirectory)/example/_output'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
