pool:
  vmImage: 'Ubuntu 16.04'

container: mabenoit/azuredevops-aksengine-agent:latest

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - example/
pr: none

variables:
  location: eastus
  apiModel: kubernetes.json
  # define 4 more variables: subscriptionId, clientId, clientSecret and dnsPrefix in the build pipeline in UI

steps:
- script: |
    aks-engine version
    cd $(system.defaultWorkingDirectory)/example
    aks-engine deploy -s $(subscriptionId) --client-id '$(clientId)' --client-secret '$(clientSecret)' --dns-prefix $(dnsPrefix) -l $(location) --api-model $(apiModel)
  displayName: 'aks-engine deploy'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts: drop'
  inputs:
    PathtoPublish: '$(system.defaultWorkingDirectory)/example/_output'
